FROM ghcr.io/voyagertechnologies-public/shire-base:0.0.0

ARG BUILDDIR=./build

# Copy built files into the image
COPY ${BUILDDIR} /app

# Set working directory
WORKDIR /app

# Set command to run
CMD ["/app/demo_cli"]
