/************************************************************************
 * SHIRE Mission SC Internal Config Values Override
 *
 * Overrides DEFAULT_SC_INTERNAL_RTS_ID_AUTO_POWER_ON to 1 so that SC
 * auto-starts RTS 001 on power-on reset, which sends the TO_LAB enable
 * command to open the debug downlink to the GSW.
 *
 * All other values forward to DEFAULT_SC_INTERNAL_* from sc_internal_cfg.h.
 ************************************************************************/
#ifndef SHIRE_SC_INTERNAL_CFG_VALUES_H
#define SHIRE_SC_INTERNAL_CFG_VALUES_H

/* Redirect SC_INTERNAL_CFGVAL to shire-specific prefix */
#define SC_INTERNAL_CFGVAL(x) SHIRE_SC_INTERNAL_##x

/* Autostart RTS 001 on power-on to enable debug downlink via TO_LAB */
#define SHIRE_SC_INTERNAL_RTS_ID_AUTO_POWER_ON  1
#define SHIRE_SC_INTERNAL_RTS_ID_AUTO_PROCESSOR 0

/* Compute correct checksums at send time; table entries use 0x00 placeholders */
#define SHIRE_SC_INTERNAL_PLATFORM_ENABLE_HEADER_UPDATE true
#define SHIRE_SC_INTERNAL_MAX_CMDS_PER_WAKEUP           DEFAULT_SC_INTERNAL_MAX_CMDS_PER_WAKEUP
#define SHIRE_SC_INTERNAL_LAST_RTS_WITH_EVENTS          DEFAULT_SC_INTERNAL_LAST_RTS_WITH_EVENTS
#define SHIRE_SC_INTERNAL_PIPE_DEPTH                    DEFAULT_SC_INTERNAL_PIPE_DEPTH
#define SHIRE_SC_INTERNAL_ATS_FILE_NAME                 DEFAULT_SC_INTERNAL_ATS_FILE_NAME
#define SHIRE_SC_INTERNAL_APPEND_FILE_NAME              DEFAULT_SC_INTERNAL_APPEND_FILE_NAME
#define SHIRE_SC_INTERNAL_RTS_FILE_NAME                 DEFAULT_SC_INTERNAL_RTS_FILE_NAME
#define SHIRE_SC_INTERNAL_ATS_TABLE_NAME                DEFAULT_SC_INTERNAL_ATS_TABLE_NAME
#define SHIRE_SC_INTERNAL_APPEND_TABLE_NAME             DEFAULT_SC_INTERNAL_APPEND_TABLE_NAME
#define SHIRE_SC_INTERNAL_RTS_TABLE_NAME                DEFAULT_SC_INTERNAL_RTS_TABLE_NAME
#define SHIRE_SC_INTERNAL_RTSINFO_TABLE_NAME            DEFAULT_SC_INTERNAL_RTSINFO_TABLE_NAME
#define SHIRE_SC_INTERNAL_RTP_CTRL_TABLE_NAME           DEFAULT_SC_INTERNAL_RTP_CTRL_TABLE_NAME
#define SHIRE_SC_INTERNAL_ATSINFO_TABLE_NAME            DEFAULT_SC_INTERNAL_ATSINFO_TABLE_NAME
#define SHIRE_SC_INTERNAL_APPENDINFO_TABLE_NAME         DEFAULT_SC_INTERNAL_APPENDINFO_TABLE_NAME
#define SHIRE_SC_INTERNAL_ATS_CTRL_TABLE_NAME           DEFAULT_SC_INTERNAL_ATS_CTRL_TABLE_NAME
#define SHIRE_SC_INTERNAL_ATS_CMD_STAT_TABLE_NAME       DEFAULT_SC_INTERNAL_ATS_CMD_STAT_TABLE_NAME
#define SHIRE_SC_INTERNAL_CONT_ON_FAILURE_START         DEFAULT_SC_INTERNAL_CONT_ON_FAILURE_START
#define SHIRE_SC_INTERNAL_TIME_TO_USE                   DEFAULT_SC_INTERNAL_TIME_TO_USE
#define SHIRE_SC_INTERNAL_MISSION_REV                   DEFAULT_SC_INTERNAL_MISSION_REV

#endif /* SHIRE_SC_INTERNAL_CFG_VALUES_H */
